mango_config_path: /home/gergon02/Dev/Personal/dotfiles
system_config_path: /home/gergon02/Dev/Personal/dotfiles
dotfiles_folders:
- name: main
  path: /
  target_path: /path/to/target/folder

- name: backup
  path: /xdg_config
  target_path: /path/to/target/folder


